name = "lean_study"
version = "0.1.0"
keywords = ["math"]
# defaultTargets = ["LeanStudy"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

# [[lean_lib]]
# name = "LeanStudy"
